# Generated by Django 4.1.3 on 2025-01-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=100)),
                ('context', models.TextField()),
                ('word', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
